name: lxd-systemd-ubuntu
on: [push]

jobs:
  ubuntu:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Install LXD
        run: |
          sudo snap install lxd --channel=latest/stable
          sudo /snap/bin/lxd waitready
          # init with dir backend (faster than zfs)
          cat <<'YAML' | sudo /snap/bin/lxd init --preseed
          config: {}
          networks:
            - name: lxdbr0
              type: bridge
              config:
                ipv4.address: auto
                ipv6.address: none
          storage_pools:
            - name: default
              driver: dir
          profiles:
            - name: default
              devices:
                root:
                  path: /
                  pool: default
                  type: disk
                eth0:
                  name: eth0
                  network: lxdbr0
                  type: nic
          YAML
          sudo lxc remote add ubuntu https://cloud-images.ubuntu.com/releases --protocol simplestreams || true

      - name: Generate ephemeral SSH keypair
        run: |
          ssh-keygen -t rsa -b 4096 -N "" -f id_rsa
          chmod 600 id_rsa

      - name: Launch Ubuntu container
        run: |
          sudo lxc launch ubuntu:22.04 sysd --config security.nesting=true
          # wait for systemd to settle
          sudo lxc exec sysd -- bash -lc 'until systemctl is-system-running --wait; do sleep 1; done || true'

      - name: Provision container
        run: |
          PUBKEY=$(cat id_rsa.pub)
          sudo lxc exec sysd -- bash -lc "
            apt-get update -y &&
            apt-get install -y openssh-server &&
            systemctl enable --now ssh &&
            mkdir -p /root/.ssh &&
            echo '$PUBKEY' > /root/.ssh/authorized_keys &&
            chmod 600 /root/.ssh/authorized_keys
          "

      - name: Run deploy commands via SSH
        run: |
          IP=$(sudo lxc list sysd -c 4 --format csv | cut -d' ' -f1)
          echo "Container IP: $IP"
          ssh -i id_rsa -o StrictHostKeyChecking=no root@"$IP" "
            echo 'hello from Ubuntu 22.04';
            hostnamectl;
            systemctl is-system-running || true
          "

      - name: Cleanup
        if: always()
        run: |
          sudo lxc delete -f sysd || true
          rm -f id_rsa id_rsa.pub