name: lxd-systemd-tests
on: [push]

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        distro: [ "ubuntu:22.04" ]

    steps:
      - uses: actions/checkout@v4

      - name: Install LXD
        run: |
          sudo snap install lxd --channel=latest/stable
          sudo /snap/bin/lxd waitready
          # simple dir backend (faster than zfs)
          cat <<'YAML' | sudo /snap/bin/lxd init --preseed
          config: {}
          networks: []
          storage_pools:
            - name: default
              driver: dir
          profiles:
            - name: default
              devices:
                root:
                  path: /
                  pool: default
                  type: disk
          cluster: null
          YAML
          # add useful remotes
          sudo lxc remote add ubuntu https://cloud-images.ubuntu.com/releases --protocol simplestreams || true
          sudo lxc remote add images https://images.linuxcontainers.org --protocol simplestreams || true
          sudo lxc remote list

      - name: Generate SSH keypair
        run: |
          ssh-keygen -t rsa -b 4096 -N "" -f id_rsa
          chmod 600 id_rsa

      - name: Launch container (${{ matrix.distro }})
        run: |
          sudo lxc launch ${{ matrix.distro }} sysd --config security.nesting=true
          # wait for systemd to settle
          sudo lxc exec sysd -- bash -lc 'until systemctl is-system-running --wait; do sleep 1; done || true'

      - name: Provision container + push key
        run: |
          PUBKEY=$(cat id_rsa.pub)
          if [[ "${{ matrix.distro }}" == ubuntu:* ]]; then
            sudo lxc exec sysd -- bash -lc "
              apt-get update -y &&
              apt-get install -y openssh-server &&
              systemctl enable --now ssh &&
              mkdir -p /root/.ssh &&
              echo '$PUBKEY' > /root/.ssh/authorized_keys &&
              chmod 600 /root/.ssh/authorized_keys
            "
          else
            sudo lxc exec sysd -- bash -lc "
              dnf -y install openssh-server ||
              yum -y install openssh-server;
              systemctl enable --now sshd &&
              mkdir -p /root/.ssh &&
              echo '$PUBKEY' > /root/.ssh/authorized_keys &&
              chmod 600 /root/.ssh/authorized_keys
            "
          fi

      - name: Run deploy commands via SSH
        run: |
          IP=$(sudo lxc list sysd -c 4 --format csv | cut -d' ' -f1)
          echo "Container IP: $IP"
          ssh -i id_rsa -o StrictHostKeyChecking=no root@"$IP" "
            echo 'hello from ${{ matrix.distro }}';
            hostnamectl;
            systemctl is-system-running || true
          "

      - name: Cleanup
        if: always()
        run: |
          sudo lxc delete -f sysd || true
          rm -f id_rsa id_rsa.pub