name: lxd-systemd-ubuntu
on: [push]

jobs:
  ubuntu:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install & init LXD (dir backend + lxdbr0)
        run: |
          sudo snap install lxd --channel=latest/stable
          sudo /snap/bin/lxd waitready
          cat <<'YAML' | sudo /snap/bin/lxd init --preseed
          config: {}
          networks:
            - name: lxdbr0
              type: bridge
              config:
                ipv4.address: auto
                ipv6.address: none
          storage_pools:
            - name: default
              driver: dir
          profiles:
            - name: default
              devices:
                root: { path: /, pool: default, type: disk }
                eth0: { name: eth0, network: lxdbr0, type: nic }
          cluster: null
          YAML
          sudo lxc remote add ubuntu https://cloud-images.ubuntu.com/releases --protocol simplestreams || true

      - name: Generate ephemeral SSH keypair
        run: |
          ssh-keygen -t rsa -b 4096 -N "" -f id_rsa
          chmod 600 id_rsa

      - name: Launch Ubuntu with cloud-init (auto-SSH)
        run: |
          PUBKEY=$(cat id_rsa.pub)
          # cloud-init: install openssh-server, add root authorized_key, enable ssh
          CI=$(cat <<EOF
          #cloud-config
          packages:
            - openssh-server
          users:
            - name: root
              ssh_authorized_keys:
                - $PUBKEY
          runcmd:
            - systemctl enable --now ssh
          EOF
          )
          sudo lxc launch ubuntu:22.04 sysd \
            --config security.nesting=true \
            --config cloud-init.user-data="$CI"

      - name: SSH in (built-in retries)
        run: |
          IP=$(sudo lxc list sysd -c 4 --format csv | awk '{print $1}')
          echo "Container IP: $IP"
          ssh -i id_rsa \
            -o StrictHostKeyChecking=no \
            -o ConnectTimeout=3 \
            -o ConnectionAttempts=10 \
            root@"$IP" "echo 'hello from ubuntu'; hostnamectl; true"

      - name: Cleanup
        if: always()
        run: |
          sudo lxc delete -f sysd || true
          rm -f id_rsa id_rsa.pub